
language: android
android:
        components:
                - platform-tools
                - build-tools-25.0.2
                - android-24
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master